name: Demo workflow
on:
  push:
    branches:
      - "dev"
      - "master"

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Push repo
        uses: actions/checkout@v3
      - name: Hello
        run: echo "Hello World!"
      
