name: Demo workflow
on: workflow_dispatch
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Hello from GitHub Actions
        run: echo "Hello GitHub Actions!"
      - name: Hello number two from GitHub Actions
        run: echo "Hello2 GitHub Actions!"
      
