name: Demo workflow
on:
  push:
    branches:
      - "dev"
      - "master"

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Push repo
        uses: actions/checkout@v3
      - name: Hello
        run: echo "Hello World!"
      - name: Install python3
        uses: actions/setup-python@v3
        with:
          python3-version: "3.12"
      - name: Install poetry
        uses: snok/install-poetry@v1
        with:
          version: latest
          virtualenvs-create: true
          virtualenvs-in-project: false
          virtualenvs-path: { cache-dir }/virtualenvs
          installer-parallel: true

      
